version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: contabilidad_postgres
    environment:
      POSTGRES_DB: contabilidad_db
      POSTGRES_USER: contabilidad_user
      POSTGRES_PASSWORD: contabilidad_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup  # Para respaldos
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: contabilidad_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@contabilidad.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local