version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: contabilidad-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/contabilidad.db:/app/contabilidad.db
      - backend_data:/app/data
    environment:
      - CORS_ORIGINS=http://localhost:4173
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
    container_name: contabilidad-frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4173"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_data:
    driver: local