[phases.setup]
nixPkgs = ["python312", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python3 migrate_to_postgresql.py"]

[start]
cmd = "python3 start.py"