[variables]
PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = ["python312", "nodejs_20", "npm-9_x"]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build-production"
]

[start]
cmd = "python3 -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"