[phases.setup]
nixPkgs = ["python312", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python3 -c 'from core.database import engine, Base; from models import models; Base.metadata.create_all(bind=engine); print(\"✅ Database initialized\")'"]

[start]
cmd = "python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"