[variables]
NODE_VERSION = "20"
PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = ["...", "nodejs_20", "python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build-production"
]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"